name: ditto-file-update
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/10 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@master
       
    - name: Setup dependencies
      run: |
        install.packages('janitor')
        install.packages("src/AzureStor.zip",lib=".",repos=NULL, verbose = TRUE)
        install.packages("tidyverse")
        install.packages("readr")
      shell: Rscript {0}
       
    - name: Update Files
      env:
          repo_token: ${{secrets.GITHUB_TOKEN}}
      run: |
        source("update_death_azure.R")
      shell: Rscript {0}
        
