name: ditto-file-update
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml:latest
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@master
       
    -name: Setup dependencies
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
       
    - name: Update Files
      env:
        repo_token: ${{secrets.GITHUB_TOKEN}}
      run: |
        echo "Running Now!"
        
